services:
  - type: web
    env: static
    name: client
    env: docker
    repo: https://github.com/devdjangoreact/render_docker.git
    buildFilter:
      paths:
        - client/**
    buildCommand: yarn && yarn build --filter=client
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_GRAPHQL_HOST
        fromService:
          name: client
          type: web
          property: host
